FROM python:3.8-slim
ENV PYTHONUNBUFFERED 1
RUN apt-get update 
RUN apt-get install -y netcat
RUN mkdir /app

ADD requirements/ /app/requirements/
RUN pip install -r app/requirements/test.txt

COPY . /app
WORKDIR /app

COPY ./entrypoint.sh /
RUN chmod +x /entrypoint.sh
ENTRYPOINT ["/entrypoint.sh"]
