version: '3.7'

networks:
  default:
    external:
      name: planner

services:
  postgres:
    image: postgres
    container_name: planner-db
    env_file:
      - ./.envs/.django
      - ./.envs/.postgres
    volumes:
      - /var/lib/postgresql/data 
    restart: unless-stopped
    ports:
      - "5432:5432"
  django:
    build: .
    container_name: planner-back
    env_file:
      - ./.envs/.django
      - ./.envs/.postgres
    volumes:
      - ./:/app
    command: bash -c "python manage.py migrate && uvicorn config.asgi:application --host 0.0.0.0 --reload"
    ports:
      - "8000:8000"
    depends_on:
      - postgres