# Generated by Django 3.1.7 on 2021-06-03 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budgetboarduser',
            name='rights',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='status',
        ),
    ]
