# Generated by Django 3.1.7 on 2021-05-02 11:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('purpose', '0002_auto_20210430_1356'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purposeresult',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='purpose',
            name='date_created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purpose',
            name='group_result_by',
            field=models.CharField(choices=[('day', 'День'), ('week', 'Неделя'), ('month', 'Месяц')], default=None, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='purpose',
            name='group_result_mode',
            field=models.CharField(choices=[('sum', 'Сумма'), ('avg', 'Среднее значение'), ('max', 'Максимальное значение'), ('min', 'Минимальное значение')], default='sum', max_length=3),
        ),
    ]
