# Generated by Django 3.1.7 on 2021-04-12 18:00

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('habit_tracker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HabitCompleteDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_done', models.BooleanField(blank=True, default=False, null=True)),
                ('date', models.DateField()),
            ],
        ),
        migrations.RenameField(
            model_name='habit',
            old_name='is_track_value',
            new_name='is_complete',
        ),
        migrations.RemoveField(
            model_name='habit',
            name='value',
        ),
        migrations.AddField(
            model_name='habit',
            name='date_created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='habit',
            name='do_on_weekdays',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(), default=[], size=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='habit',
            name='description',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.DeleteModel(
            name='HabitComplete',
        ),
        migrations.AddField(
            model_name='habitcompleteday',
            name='habit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='habit_tracker.habit'),
        ),
    ]
